### ISSUE TITLE
PyPI version 1.0.2 appears to be missing 'hotpie.py'

### ISSUE THREAD

**Issue by software-opal** [gingerlime/hotpie#8]
Hey, your library is awesome and I'd love to use the latest version; but installing it from PyPI with `pip` results in the `hotpie.py` file not being installed. I've just quickly checked the [source distribution URL](https://files.pythonhosted.org/packages/90/ea/4faebd8f70702cf0f9cceb644500d3a35dd71b9b4676ea81d037bc93dadf/hotpie-1.0.2.tar.gz) listed during the install and it is definitely missing the `hotpie.py` file.

**Comment by gingerlime** [comment]
Thanks for spotting this @leesdolphin. I'm not terribly familiar with the whole setup.py / pypi shenanigans, so I must have missed something when "borrowing" setup.py from another package. I'll see if I can figure out how to make it pick up the hotpie.py file.

**Comment by gingerlime** [comment]
@leesdolphin I updated pypi to `1.0.5` and hopefully now things should work again. Can you give it a try?

**Comment by software-opal** [comment]
Thank you so much; it's working beautifully.
